export const ENDPOINTS = {
  BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:3000',
  AUTH_ME: '/auth/me',
  AUTH_SESSION: '/auth/session',
  AUTH_LOGOUT: '/auth/logout',
  OAUTH_GOOGLE_AUTHORIZATION: '/auth/google/authorization',
  OAUTH_GOOGLE_CALLBACK: '/auth/google/callback',
  OAUTH_MICROSOFT_AUTHORIZATION: '/auth/microsoft/authorization',
  OAUTH_MICROSOFT_CALLBACK: '/auth/microsoft/callback',
  AUTH_CHECK_EMAIL: '/auth/check-email',
  ONBOARDING: '/onboarding',
  INVITEUSER: '/invite',
  ACCEPTINVITATION: (token: string) => `/invitations/${token}/accept`,
  WORKSPACES: '/workspace',
  WORKSPACE_DETAIL: (workspaceUid: string) => `/workspace/${workspaceUid}`,
  WORKSPACE_MEMBERS: (workspaceId: string) => `/workspace/${workspaceId}/members`,
} as const;
